// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewOrganisation struct {
	Name string `json:"name"`
}

type Organisation struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (Organisation) IsEntity() {}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

func (User) IsEntity() {}
